default_stages: [pre-push]
repos:
- repo: local
  hooks:
    - id: make-lint
      name: "Run make lint"
      entry: make lint
      language: system
      pass_filenames: false
      stages: [pre-push]